# Generated by Django 5.0.6 on 2024-05-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.RemoveField(
            model_name='group',
            name='created',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='group',
            name='updated',
        ),
    ]
